import pyautogui as p
import time as t
from win10toast import ToastNotifier

def toast(message):
	toaster = ToastNotifier()
	toaster.show_toast(message)

def job():
    # call(['python', 'testgql.py'])
    toast("YOU HAVE 15 seconds to check each picture")
    
p.click(508,21)
p.hotkey("f5")
t.sleep(2)
p.click(button='right', x=574, y=238)
p.click(644,253)
p.click(button='right', x=570, y=340)
p.click(635,352)
p.click(button='right', x=569, y=430)
p.click(646,448)
t.sleep(2)
p.hotkey("ctrl", "tab")
p.hotkey("ctrl", "tab")
t.sleep(2)
p.click(598,241)
p.hotkey("ctrl", "tab")
t.sleep(2)
p.click(598,241)
p.hotkey("ctrl", "tab")
t.sleep(2)
p.click(598,241)
t.sleep(2)
p.hotkey("ctrl", "tab"); p.hotkey("ctrl", "tab"); p.hotkey("ctrl", "tab")
job()
t.sleep(1)
p.hotkey("esc")
t.sleep(2)
p.scroll(100)
t.sleep(2)
p.hotkey("a")
t.sleep(2)
p.write("sheryl")
t.sleep(2)
p.hotkey("enter")
t.sleep(2)
p.click(984,612)
t.sleep(2)
p.write('Hi Sheryl Patalen,\nIt is a false positive. The difference between the lighting in the room was the main issue that the cctv detected.\nRequesting for your review\n\nThank you!\nRegards,')
t.sleep(2)
p.hotkey("alt", "s")
t.sleep(2)
p.hotkey("ctrl", "w")
job()
t.sleep(2)
p.hotkey("esc")
t.sleep(2)
p.scroll(100)
t.sleep(2)
p.hotkey("a")
t.sleep(2)
p.write("sheryl")
t.sleep(1)
p.hotkey("enter")
t.sleep(1)
p.click(984,612)
t.sleep(2)
p.write('Hi Sheryl Patalen,\nIt is a false positive. The difference between the lighting in the room was the main issue that the cctv detected.\nRequesting for your review\n\nThank you!\nRegards,')
t.sleep(2)
p.hotkey("alt", "s")
t.sleep(2)
p.hotkey("ctrl", "w")
job()
t.sleep(2)
p.hotkey("esc")
t.sleep(2)
p.scroll(100)
t.sleep(2)
p.hotkey("a")
t.sleep(2)
p.write("sheryl")
t.sleep(2)
p.hotkey("enter")
t.sleep(2)
p.click(984,612)
t.sleep(2)
p.write('Hi Sheryl Patalen,\nIt is a false positive. The difference between the lighting in the room was the main issue that the cctv detected.\nRequesting for your review\n\nThank you!\nRegards,')
t.sleep(2)
p.hotkey("alt", "s")
t.sleep(2)
p.hotkey("ctrl", "w")