#!/bin/bash
clear

# shameless taken from @g0tmilk kali os-scripts
#### (Cosmetic) Colour output
RED="\033[01;31m"      # Issues/Errors
GREEN="\033[01;32m"    # Success
YELLOW="\033[01;33m"   # Warnings/Information
BLUE="\033[01;34m"     # Heading
BOLD="\033[01;01m"     # Highlight
RESET="\033[00m"       # Normal

# also shamelesly ganked from a stack overflow post at http://stackoverflow.com/questions/10458743/bash-reading-text-from-a-string-one-character-at-a-time-with-whitespace
# ascii art generated by Jp2a program by Christian Stigen Larsen at https://csl.name/jp2a/

#
## In addition to having shamelessly taken for a tribute to geekism on May 25, 2021 by @dark_axl.
## Original bash script → https://gist.github.com/cyberkryption/07aea3055aff9f31d0ff20136a31f83b
#

function typewriter
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${text:$i:1}"
        sleep ${delay}
    done
}

function typewriter_red
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${RED}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_yellow
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${YELLOW}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_green
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${GREEN}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_blue
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${BLUE}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_bold
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${BOLD}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

clear
echo # <-- Just for a newline
echo # <-- Just for a newline
echo -e "$RESET ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "$GREEN                       __         .__.__                             .__     __  .__  .__ "   
echo -e "$RESET _______  ____   _____/  |________|__|  |   __________   ____   ____ |  |___/  |_|  | |__|"  
echo -e "$GREEN \_  __ \/  _ \ /  _ \   __\___   /  |  |  /  _ \\____ \ /  _ \_/ ___\|  |  \   __\  | |  |"      
echo -e "$RESET  |  | \(  <_> |  <_> )  |  /    /|  |  |_(  <_> )  |_> > <_> )  \___|   Y  \  | |  |_|  |"   
echo -e "$GREEN  |__|   \____/ \____/|__| /_____ \__|____/\____/|  __/ \____/ \___  >___|  /__| |____/__|"  
echo -e "$RESET                                 \/              |__|              \/     \/              "  
echo -e "$GREEN ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

sleep 1
echo # <-- Just for a newline
typewriter_bold "                            Presents...." .1
echo # <-- Just for a newline
typewriter_bold "               A Star Wars themed hacking challenge." .1
echo # <-- Just for a newline
typewriter_bold "                        The story so far................" .1
echo # <-- Just for a newline
sleep 1
clear

echo -e -n "             _____\r\n"
echo -e -n "         ___/O   O\____\r\n"
echo -e -n "        / O        O   \\r\n"
echo -e -n "        \______________/\r\n"
echo -e -n "   -===|____\///\\\/_____\r\n"
echo -e -n "       \----------------/\r\n"
echo -e -n "        \______________/  \/\r\n"
echo -e -n "         /\__________/    //\r\n"
echo -e -n "  >=o\  // //\\   || \\  //\r\n"
echo -e -n "     \\o/ //  \o  ||  \o//\r\n"
echo -e -n "         //    || ||\r\n"
echo -e -n "     /o==o     |o \o==o   \r\n"
echo -e -n "    //         //     \\\r\n"
echo -e -n "    /\        //       /\ \r\n"
echo -e -n "              /\          \r\n"
echo -e -n "   \r\n"

typewriter_red "Empire Malware Agent Manager: " .1
typewriter "Hoth Edition V1.0.9 Beta" .1
echo # <-- Just for a newline
typewriter_red "Injecting Malware : " .1
typewriter "Empire Metasploit Implant - Credentials Recovery  and Recon 3.0" .1
echo # <-- Just for a newline
typewriter_blue "[+] Acquiring process handle ...." .1
echo # <-- Just for a newline
typewriter_blue "[+] Exploit - Malware Injected Successfully...Credential recovery beginning ...." .1
echo # <-- Just for a newline
typewriter_yellow "[+] Usernames ..." .1
echo # <-- Just for a newline
typewriter_yellow "[+] leah_organa,ben_kenobi,luke_skywalker,han_solo" .1
echo # <-- Just for a newline
typewriter_yellow "[+] artoo_detoo,c_three_pio,chewbacca,lando_calrissian" .1
echo # <-- Just for a newline
typewriter_blue "[+] Passwords ..." .1
echo # <-- Just for a newline
typewriter_blue "[+] use_the_f0rce,corellian1,not-a-slug12,hanShotFirst!,rwaaaaawr5," .1
echo # <-- Just for a newline
typewriter_blue "[+] mesah_p@ssw0rd,thats_no_moon,beep_b00p,sh00t-first,help_me_obiw@n" .1
echo # <-- Just for a newline
typewriter_red "[+] Usernames Yoda not found ..." .1
echo # <-- Just for a newline
typewriter_red "[+] Searching ..." .1
echo # <-- Just for a newline
typewriter_yellow "[+] UDP Flood inbound - Flood protection starting ..." .1
echo # <-- Just for a newline
typewriter_yellow "[+] Exception Error in stack frame - 0x900x90Yoda" .1
echo # <-- Just for a newline
typewriter_yellow "[+] Program terminated." .1
echo # <-- Just for a newline
typewriter_red " Implant communication lost - Empire Malware Agent failed" .1
echo # <-- Just for a newline

clear
typewriter " Meanwhile, the Empire is not happy " .1 
echo # <-- Just for a newline
typewriter " and is holding a meeting with Lord Vader.......... " .1
echo # <-- Just for a newline

typewriter_yellow "[+] Connecting to : 13.37.13.37.." .1
echo # <-- Just for a newline

typewriter_yellow "[+] Generating encryption keys - Death Star Protocol - 4096 bits" .1
echo # <-- Just for a newline
sleep 1
typewriter_green "[+] Secure communications establishing ..." .1
echo # <-- Just for a newline
clear
echo -e -n "           .          .\r\n"
echo -e -n " .          .                  .          .              .\r\n"
echo -e -n "       +.           _____  .        .        + .                    .\r\n"
echo -e -n "   .        .   ,-~s'     '~-.                                +\r\n"
echo -e -n "              ,^ ___         ^. +                  .    .       .\r\n"
echo -e -n "             / .^   ^.         \         .     .\r\n"
echo -e -n "            Y  l  o  !          Y  .                .    .       .\r\n"
echo -e -n "    .       l_ '.___.'        __[             .    .       .         +\r\n"
echo -e -n "            |^~'-----------''~ ^|       +             .    .       .\r\n"
echo -e -n "  +       . !                   !     .        .    .       .       .\r\n"
echo -e -n "         .   \                 /                 .    .       .   \r\n"
echo -e -n "              ^.             .^            .          +.\r\n"
echo -e -n "                "-.._____.,-" .                    .\r\n"
echo -e -n "         +           .                .   +                       .\r\n"
echo -e -n "  +          .             +                                  .\r\n"
echo # <-- Just for a newline
typewriter_red "Death Star IRC Server V.101 : " .1
typewriter "Darkside Edition V9.26 Final." .1
echo # <-- Just for a newline
typewriter_red "Communications protocol : " .1
typewriter "IronFist SSH V2.0 protocol 3.0" .1
echo # <-- Just for a newline
typewriter_red "Awaiting Clients ...." .1
echo # <-- Just for a newline
sleep 1
typewriter_blue "<LordVader>" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
typewriter_blue "<Empire_1 >" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
typewriter_blue "<Empire_2 >" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
typewriter_blue "<Empire_3 >" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Morning Cadets. I want the Rebel Alliance plans." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Our malware was detected by the Rebels due to an agent failing me." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " He is no longer with us." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " I feel this distrubance in the force was caused by Yoda." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " He has interferred in Imperial business for the last time." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Our malware did tell us that vital information is hidden" .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " in files on the Rebel Alliance servers called secrets.txt" .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " The Rebel Alliance will no doubt have increased their defenses," .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " you will overcome them." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " The Rebel Alliance is using the 192.168.1.1 - 192.168.1.254 range for their network." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Malware Report: Rebel defenses detected at 192.168.1.1, 192.168.1.120," .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter "                 192.168.1.130 and 192.168.1.251." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " DO NOT SCAN THEM, unless you want to incurr my wrath!!!" .1 
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " We have instructions for our new security tools on your desktop." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Report any tools related issues immediately to your designated handler." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter_yellow " Bring me Yoda's plans NOW. DO NOT FAIL ME !!!!!! " .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter_red " Bring me Yoda's plans NOW. DO NOT FAIL ME !!!!!! " .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Out. Communication terminated." .1
echo # <-- Just for a newline
sleep 5